[package]
name = "mol-parsing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1"
pest = "2"
pest_derive = "2"
serde = "1"
serde_json = "1"
